# Generated by Django 6.0.2 on 2026-02-27 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_alter_enrollment_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='enrollment',
            name='unique_enrollment',
        ),
    ]
