# Generated by Django 6.0.2 on 2026-02-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='lecture_type',
            field=models.CharField(default='video', max_length=20),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]